# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.define "web", autostart: true do |web|
    web.vm.box = "generic/ubuntu2004"
    web.vm.box_version = "3.6.14"
    web.vm.network "public_network", ip: "192.168.0.233", bridge: "Qualcomm QCA61x4A 802.11ac Wireless Adapter"
  end

  config.vm.define "zabbix", autostart: true do |zabbix|
    zabbix.vm.box = "generic/ubuntu2004"
    zabbix.vm.box_version = "3.6.14"
    zabbix.vm.network "public_network", ip: "192.168.0.234", bridge: "Qualcomm QCA61x4A 802.11ac Wireless Adapter"
  end

  config.vm.define "database", autostart: true do |database|
    database.vm.box = "generic/ubuntu2004"
    database.vm.box_version = "3.6.14"
    database.vm.network "public_network", ip: "192.168.0.235", bridge: "Qualcomm QCA61x4A 802.11ac Wireless Adapter"
  end

  config.vm.define "grafana", autostart: true do |grafana|
    grafana.vm.box = "generic/ubuntu2004"
    grafana.vm.box_version = "3.6.14"
    grafana.vm.network "public_network", ip: "192.168.0.236", bridge: "Qualcomm QCA61x4A 802.11ac Wireless Adapter"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--paravirtprovider", "kvm"]
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    echo "root:test" | chpasswd
    useradd -s /bin/bash -p $(perl -e 'print crypt($ARGV[0], "password")' 'test') -m -N -G adm,vagrant,sudo test
  SHELL
end
